steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -eux

        # cloudbuild doesn't check out the .git directory with full history
        # MAYBE 2025-cloudbuild [supports git history](https://cloud.google.com/build/docs/building/manage-dependencies) with `depth: -1` so try removing workaround:
        shopt -s dotglob && rm -rf *
        git init
        git remote add origin https://github.com/darthwalsh/FireSocket.git
        git fetch origin
        git checkout $BRANCH_NAME
        git reset --hard $COMMIT_SHA
  - name: "gcr.io/$PROJECT_ID/npm-with-java"
    args: ["install"]
  - name: "gcr.io/$PROJECT_ID/npm-with-java"
    args: ["run", "build"]
  - name: "gcr.io/$PROJECT_ID/npm-with-java"
    args: ["test"]
  - name: "gcr.io/$PROJECT_ID/npm-with-java"
    args: ["run", "semantic-release"]
    secretEnv: ["GH_TOKEN", "NPM_TOKEN"]
secrets:
  - kmsKeyName: projects/firesocket-test/locations/global/keyRings/ring/cryptoKeys/key
    secretEnv:
      GH_TOKEN: "CiQA9ejEtnIYCCaPyQyjeqCkcxdQz5zCEI/Nys9K/b9vp5KEqQ4SUQB0N8tI8si1PNyHEoIO4uaxYewf2h0UIeJJSNHfrETr5j5p7Sjw/9lZUd6lyR/wvDHzli2SlY0fc5ZaeIGETl4ycroc1jId6VBti0UFl3y5Eg=="
      NPM_TOKEN: "CiQA9ejEtlgkk+t0zVzd1UbjeBiGlSiiyi9Wli47jBYz0VNaXkkSTQB0N8tISxOa+mJQw6KGg352xRUXu7M5F/30u3nkCHvAC7PftbApWsnbLJmMYg+zJhn1AqnmFB7XN1lDQs1AgFXjdUyni1RhR6phwb9T"
